@echo off
REM ============================================================
REM GuardianShield V1 Build + Test Verification Script
REM Generated by Atlas (Sisyphus orchestrator)
REM Run this on the target Windows machine with VS2022 installed
REM ============================================================

setlocal enabledelayedexpansion

set PROJECT_ROOT=%~dp0..
set BUILD_DIR=%PROJECT_ROOT%\build
set LOG_DIR=%PROJECT_ROOT%\.sisyphus\evidence

echo ============================================================
echo GuardianShield V1 Build + Test Verification
echo Project: %PROJECT_ROOT%
echo Time: %DATE% %TIME%
echo ============================================================

REM Create evidence directory
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

REM Step 1: CMake Configure
echo.
echo [STEP 1] CMake Configure...
cmake -B "%BUILD_DIR%" -G "Visual Studio 17 2022" -A x64 -DBUILD_TESTS=ON -DBUILD_TOOLS=ON 2>&1 | tee "%LOG_DIR%\task-16-cmake-configure.txt"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] CMake configure failed
    exit /b 1
)
echo [PASS] CMake configure succeeded

REM Step 2: Build Release
echo.
echo [STEP 2] Building Release...
cmake --build "%BUILD_DIR%" --config Release 2>&1 | tee "%LOG_DIR%\task-16-build.txt"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] Build failed
    exit /b 1
)
echo [PASS] Build succeeded

REM Step 3: Check for warnings
echo.
echo [STEP 3] Checking for /W4 warnings...
findstr /i "warning C" "%LOG_DIR%\task-16-build.txt" > "%LOG_DIR%\task-16-warnings.txt"
for /f %%i in ('type "%LOG_DIR%\task-16-warnings.txt" ^| find /c /v ""') do set WARN_COUNT=%%i
echo Warning count: %WARN_COUNT%
if %WARN_COUNT% gtr 0 (
    echo [WARN] %WARN_COUNT% compiler warnings found - review task-16-warnings.txt
) else (
    echo [PASS] Zero compiler warnings
)

REM Step 4: Run all tests
echo.
echo [STEP 4] Running all tests...
ctest --test-dir "%BUILD_DIR%" --config Release --output-on-failure 2>&1 | tee "%LOG_DIR%\task-16-test-results.txt"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] Some tests failed - review task-16-test-results.txt
    exit /b 1
)
echo [PASS] All tests passed

REM Step 5: Count test results
echo.
echo [STEP 5] Test summary...
findstr "tests passed" "%LOG_DIR%\task-16-test-results.txt"
findstr "tests failed" "%LOG_DIR%\task-16-test-results.txt"

REM Step 6: Security verification
echo.
echo [STEP 6] Security verification...
echo Checking hardcoded HMAC key removed...
findstr /c:"GuardianShield_IPC_v2" "%PROJECT_ROOT%\src\service\common\src\ipc.cpp"
if %ERRORLEVEL% equ 0 (
    echo [FAIL] Hardcoded HMAC key still present!
    exit /b 1
) else (
    echo [PASS] Hardcoded HMAC key removed
)

echo Checking Global mutex in GuardianA...
findstr /c:"GuardianShield-Leader" "%PROJECT_ROOT%\src\service\GuardianA\src\guardian_a.cpp"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] Global mutex not found in GuardianA!
    exit /b 1
) else (
    echo [PASS] Global mutex present in GuardianA
)

echo Checking Global mutex in GuardianB...
findstr /c:"GuardianShield-Leader" "%PROJECT_ROOT%\src\service\GuardianB\src\guardian_b.cpp"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] Global mutex not found in GuardianB!
    exit /b 1
) else (
    echo [PASS] Global mutex present in GuardianB
)

echo Checking ETW orphan recovery...
findstr /c:"ERROR_ALREADY_EXISTS" "%PROJECT_ROOT%\src\service\GuardianA\src\guardian_a.cpp"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] ETW orphan recovery not found!
    exit /b 1
) else (
    echo [PASS] ETW orphan recovery present
)

echo Checking SHA256File implementation...
findstr /c:"BCryptCreateHash" "%PROJECT_ROOT%\src\service\common\src\security.cpp"
if %ERRORLEVEL% neq 0 (
    echo [FAIL] SHA256File BCrypt implementation not found!
    exit /b 1
) else (
    echo [PASS] SHA256File BCrypt implementation present
)

echo.
echo ============================================================
echo VERIFICATION COMPLETE
echo Build: PASS
echo Tests: PASS
echo Security: PASS
echo ============================================================
echo Evidence saved to: %LOG_DIR%
echo.

endlocal
exit /b 0
